apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: zara
  namespace: tsm
  labels:
    team: tsm
spec:
  port: 3000
  replicas:
    min: 1
    max: 2
  ingresses:
    - 'https://zara.intern.dev.nav.no'
    - 'https://zara.ansatt.dev.nav.no'
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: trygdeetaten.no
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /api/*
        - /favicon.ico
  valkey:
    - instance: syk-inn
      access: readwrite
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: loki
  prometheus:
    enabled: true
    path: /api/internal/metrics
  liveness:
    path: /api/internal/is_alive
  readiness:
    path: /api/internal/is_ready
  preStopHook:
    http:
      path: /api/internal/pre_stop
  filesFrom:
    - emptyDir:
        medium: Memory
      mountPath: /app/.next/cache
  accessPolicy:
    outbound:
      external:
        - host: cdn.nav.no
        - host: api.slack.com
      rules:
        - application: logging
          namespace: nais-system
  resources:
    requests:
      cpu: 50m
      memory: 200Mi
  envFrom:
    - secret: tsm-zara-secrets
