apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: zara
  namespace: tsm
  labels:
    team: tsm
spec:
  port: 3000
  replicas:
    min: 2
    max: 2
  ingresses:
    - 'https://zara.intern.nav.no'
    - 'https://zara.ansatt.nav.no'
  azure:
    application:
      enabled: true
      tenant: nav.no
      claims:
        groups:
          # EntraAD: nais-team-tsm
          - id: '35c70ac7-e8e6-4cec-933b-86106a97c0d4'
          # EntraAD: teamsykmelding
          - id: '3a541678-8965-45c4-844b-486a8b9b94a3'
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /api/*
        - /favicon.ico
  valkey:
    - instance: syk-inn
      access: read
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: loki
  prometheus:
    enabled: true
    path: /api/internal/metrics
  liveness:
    path: /api/internal/is_alive
  readiness:
    path: /api/internal/is_ready
  preStopHook:
    http:
      path: /api/internal/pre_stop
  filesFrom:
    - emptyDir:
        medium: Memory
      mountPath: /app/.next/cache
  accessPolicy:
    outbound:
      external:
        - host: cdn.nav.no
        - host: api.slack.com
      rules:
        - application: logging
          namespace: nais-system
  resources:
    requests:
      cpu: 50m
      memory: 200Mi
  envFrom:
    - secret: tsm-zara-secrets
