apiVersion: data.nais.io/v1
kind: Postgres
metadata:
  name: zara-postgres
  namespace: tsm
spec:
  cluster:
    majorVersion: '17'
    resources:
      cpu: 500m
      diskSize: 5Gi
      memory: 1Gi
